name: Deploy to AWS
on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create application-secret.properties
        run: |
          cat << EOF > src/main/resources/application-secret.properties
          # RDS
          spring.datasource.url=${{ secrets.RDS_URL }}
          spring.datasource.username=${{ secrets.RDS_USERNAME }}
          spring.datasource.password=${{ secrets.RDS_PASSWORD }}

          # JWT
          jwt.secret-key=${{ secrets.JWT_SECRET_KEY }}
          jwt.access-token-expiration=${{ secrets.JWT_ACCESS_TOKEN_EXPIRATION }}
          jwt.refresh-token-expiration=${{ secrets.JWT_REFRESH_TOKEN_EXPIRATION }}

          # Kakao
          kakao.client.id=${{ secrets.KAKAO_CLIENT_ID }}
          kakao.redirect.uri=${{ secrets.KAKAO_REDIRECT_URI }}
          EOF


      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/review-backend:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # 최신 이미지 pull
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/review-backend:latest
            
            # 기존 컨테이너 중지 및 삭제
            docker stop backend-container || true
            docker rm backend-container || true
            
            # 새 컨테이너 실행
            docker run -d \
              --name backend-container \
              -p 8080:8080 \
              ${{ secrets.DOCKERHUB_USERNAME }}/review-backend:latest